version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: expensetracker
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tracker" ]
      interval: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app-container
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expensetracker
      SPRING_DATASOURCE_USERNAME: tracker
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    restart: always

volumes:
  postgres-data:
