logging:
  level:
    org:
      springframework:
        web:
          servlet: debug
spring:
  application:
    name: PproProjektExpenseTracker

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  liquibase:
    change-log: classpath:liquibase/changelog-main.yaml
    enabled: true
    contexts: dev
    default-schema: public
    drop-first: false
    parameters:
      longType: bigint
      stringType: varchar(255)
      bigStringType: varchar(65000)
      dateType: date
      zoneDateTimeType: timestamp #Změnit pro postgress pro offsetdatetime
      doubleType: double